/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  ListRecipesRecipesGetParams,
  RecipeSchema
} from './';

import { axiosInstance } from './axios-instance';


type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




/**
 * @summary List Recipes
 */
export const listRecipesRecipesGet = (
    params?: ListRecipesRecipesGetParams,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<RecipeSchema[]>(
      {url: `/recipes/`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getListRecipesRecipesGetQueryKey = (params?: ListRecipesRecipesGetParams,) => {
    return [
    `/recipes/`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListRecipesRecipesGetQueryOptions = <TData = Awaited<ReturnType<typeof listRecipesRecipesGet>>, TError = HTTPValidationError>(params?: ListRecipesRecipesGetParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listRecipesRecipesGet>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListRecipesRecipesGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listRecipesRecipesGet>>> = ({ signal }) => listRecipesRecipesGet(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listRecipesRecipesGet>>, TError, TData> & { queryKey: QueryKey }
}

export type ListRecipesRecipesGetQueryResult = NonNullable<Awaited<ReturnType<typeof listRecipesRecipesGet>>>
export type ListRecipesRecipesGetQueryError = HTTPValidationError


/**
 * @summary List Recipes
 */

export function useListRecipesRecipesGet<TData = Awaited<ReturnType<typeof listRecipesRecipesGet>>, TError = HTTPValidationError>(
 params?: ListRecipesRecipesGetParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listRecipesRecipesGet>>, TError, TData>, }
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListRecipesRecipesGetQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get Recipe
 */
export const getRecipeRecipesRecipeIdGet = (
    recipeId: number,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<RecipeSchema>(
      {url: `/recipes/${recipeId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetRecipeRecipesRecipeIdGetQueryKey = (recipeId?: number,) => {
    return [
    `/recipes/${recipeId}`
    ] as const;
    }

    
export const getGetRecipeRecipesRecipeIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getRecipeRecipesRecipeIdGet>>, TError = HTTPValidationError>(recipeId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getRecipeRecipesRecipeIdGet>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRecipeRecipesRecipeIdGetQueryKey(recipeId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRecipeRecipesRecipeIdGet>>> = ({ signal }) => getRecipeRecipesRecipeIdGet(recipeId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(recipeId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRecipeRecipesRecipeIdGet>>, TError, TData> & { queryKey: QueryKey }
}

export type GetRecipeRecipesRecipeIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getRecipeRecipesRecipeIdGet>>>
export type GetRecipeRecipesRecipeIdGetQueryError = HTTPValidationError


/**
 * @summary Get Recipe
 */

export function useGetRecipeRecipesRecipeIdGet<TData = Awaited<ReturnType<typeof getRecipeRecipesRecipeIdGet>>, TError = HTTPValidationError>(
 recipeId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getRecipeRecipesRecipeIdGet>>, TError, TData>, }
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetRecipeRecipesRecipeIdGetQueryOptions(recipeId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



