/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { RecipeSchemaDescription } from './recipeSchemaDescription';
import type { RecipeSchemaFilePath } from './recipeSchemaFilePath';
import type { RecipeSchemaContent } from './recipeSchemaContent';
import type { TagSchema } from './tagSchema';

export interface RecipeSchema {
  /** Unique identifier for the recipe */
  id: number;
  /** Title of the recipe */
  title: string;
  /** Description of the recipe */
  description?: RecipeSchemaDescription;
  /** Path to the markdown file for the recipe */
  file_path?: RecipeSchemaFilePath;
  /** Markdown content of the recipe */
  content?: RecipeSchemaContent;
  /** List of tags associated with the recipe */
  tags?: TagSchema[];
}
