/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Path to the markdown file for the recipe
 */
export type RecipeSchemaFilePath = string | null;
